package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"log"
	"project/graph/model"
)

// GetTodo is the resolver for the getTodo field.
func (r *queryResolver) GetTodo(ctx context.Context) ([]*model.Todo, error) {

	type Todo struct {
		ID int `bson:"ID"`
		Name string `bson:"Name"`

	}

	t := []Todo {
		{ID: 1452, Name: "Limuthu"},
		{ID: 2, Name: "Manith"},
		{ID: 52, Name: "Yasith"},
		{ID: 52, Name: "Sandeepa"},
		{ID: 142, Name: "Induware"},

	}

	var todos  []*model.Todo

	var todos1  []*model.Todo

	
	for _, v := range t {

		
			return append(todos, &model.Todo{
				ID: int32(v.ID),
				Name: v.Name,
			}), nil
			
		

		

	}

	defer log.Println(todos1)




	
	

	return todos1, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
