package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

    "project/graph/get"

	"project/graph/model"

)


// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, cursor string) ([]*model.User, error) {
	get.Users(r, ctx)
	
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) Todo(ctx context.Context, id int32) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))

}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {





	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
