package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"project/graph/model"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, cursor string) ([]*model.User, error) {
	if r.Mongo == nil {
		return nil, fmt.Errorf("mongo client is nil — server misconfigured")
	}

	collection := r.Mongo.Database("sample_mflix").Collection("users")

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	opts := options.Find().
		SetSort(bson.D{{Key: "_id", Value: 1}}).
		SetLimit(20)

	filter := bson.M{}

	if cursor != "" {
		objectID, err := bson.ObjectIDFromHex(cursor)
		if err != nil {
			return nil, fmt.Errorf("invalid cursor ObjectID: %w", err)
		}
		filter["_id"] = bson.M{"$gt": objectID}
	}

	cur, err := collection.Find(ctx, filter, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch users: %w", err)
	}
	defer cur.Close(ctx)

	type dbUser struct {
		ID    bson.ObjectID `bson:"_id"`
		Name  string        `bson:"name"`
		Email string        `bson:"email"`
	}

	var users []*model.User

	for cur.Next(ctx) {
		var u dbUser
		if err := cur.Decode(&u); err != nil {
			return nil, fmt.Errorf("decode user: %w", err)
		}

		users = append(users, &model.User{
			ID:    u.ID.Hex(),
			Name:  u.Name,
			Email: u.Email,
		})
	}

	if err := cur.Err(); err != nil {
		return nil, fmt.Errorf("cursor error: %w", err)
	}

	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Users1 is the resolver for the users1 field.
func (r *queryResolver) Users1(ctx context.Context, cursor string, filter string, category string) ([]*model.User, error) {

	type UserGame struct {
		id string `bson:"id"`
		name string `bson:"name"`
		age int `bson:"age"`
	}

	var usergame =  UserGame {
		id: "hello",
		name: "Limuthu",
		age: 21,
	}

	var userModel []*model.User


	for i := 0; i <= 20; i++ {
		
			userModel = append(userModel, &model.User{
		
				ID: usergame.id,
				Name: usergame.name,

				
		
		
			})
		
	}
	return userModel, nil

	panic(fmt.Errorf("not implemented: Users1 - users1"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
