// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cars struct {
	ID string `json:"id"`
}

type Query struct {
}

type Todo struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
